Repository kyma-as/api-dashboard, pull requests merged in 2019-05, with the labels that each got.

#34 Implement graphs
  package.json
  public/index.html
  src/App.vue
  src/api/apiCalls.js
  src/background.js
  src/components/Graphs/BarChart.js
  src/components/Graphs/LineChart.js
  src/components/Graphs/PieChart.js
  src/components/NavDrawer.vue
  src/components/VesselCard.vue
  src/main.js
  src/plugins/vuetify.js
  src/scripts/authentication.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/store/state.js
  src/views/Login.vue
  src/views/Vessel.vue
  src/views/Vessels.vue
  yarn.lock
Labels: bug, enhancement

#35 Fixed blank startup screen
  src/main.js
Labels: bug

#36 Version 0.2
  .gitignore
  README.md
  package.json
  public/index.html
  src/App.vue
  src/background.js
  src/components/AppTitle.vue
  src/components/Graf.vue
  src/components/Graphs/BarChart.js
  src/components/Graphs/LineChart.js
  src/components/Graphs/PieChart.js
  src/components/NavBar.vue
  src/components/NavDrawer.vue
  src/components/VesselCard.vue
  src/main.js
  src/plugins/vuetify.js
  src/router.js
  src/scripts/authentication.js
  src/store.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/store/state.js
  src/views/Home.vue
  src/views/Login.vue
  src/views/Vessel.vue
  src/views/Vessels.vue
  yarn.lock
Labels: enhancement

#37 Implement graphs
  src/components/Graphs/BarChartDistance.js
  src/components/Graphs/BarChartEmission.js
  src/store/actions.js
  src/store/getters.js
  src/views/Vessel.vue
Labels: enhancement

#38 Gui
  src/components/GrannyPicker.vue
  src/components/GraphCard.vue
  src/components/NavDrawer.vue
  src/components/TimePicker.vue
  src/views/Vessel.vue
  src/views/Vessels.vue
Labels: enhancement

#41 Granularity options
  src/components/Graphs/BarChartEmission.js
  src/components/Graphs/LineChart.js
  src/store/getters.js
  src/store/mutations.js
Labels: enhancement

#43 Gui
  src/components/DateTime.vue
  src/components/FromDate.vue
  src/components/GraphCard.vue
  src/components/Graphs/BarChart.js
  src/components/Graphs/BarChartAar.js
  src/components/Graphs/LineChart.js
  src/components/TimePicker.vue
  src/components/ToDate.vue
  src/components/VesselCard.vue
  src/views/Vessel.vue
Labels: enhancement

#44 Login feedback
  src/components/NavBar.vue
  src/scripts/authentication.js
  src/store/actions.js
  src/store/mutations.js
  src/store/state.js
  src/views/Login.vue
Labels: enhancement

#51 Develop
  src/assets/ship.png
  src/assets/vessel.png
  src/background.js
  src/components/VesselCard.vue
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/state.js
  src/views/Login.vue
  src/views/Vessels.vue
Labels: enhancement

#52 Fix csv
  src/background.js
  src/components/VesselCard.vue
  src/views/Csv.vue
Labels: bug, enhancement
